# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=pax

matrix:
  include:

    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: "nFfPPHnMa47C639rS0j8YHNNrj31tJzewj5YgJDXHEqlIprGjSGoO3g8Y54R6ztCGYrVzfFFPjz5PjcScuvQlRO3+jNAZyGN9NLoWgz5DnOVPdvc24op7CkUXuRcqZpLZn5n9F0dH+ZO9AvrN9LhlarmNCvuO/obCiNaiR72zfzcGUiCS/iSHhES9nG0CQB+084T2CUMLIvG6mtYmqBpi1alTiZ9ACMNPr7qym7oLUv04OY66HmOMBnBt6uLkUJfATDuAL2Qz81ShjnbmWQOGeHuu7eCq5iSni3Hx+q388VsuA8oc7Gzr8O6BttJRzU4pfSBXDUoXHphRT4ZftvSYLg3wkmFeTXn0XfZtMzz4oMzQFdAwErLVlUAsbJ/Tv71xLooXGcftreLNPuJCaBMjZptbe1kY38mAoR6JbI4auyziJoyiurFXvP6Af+28H/vE3V56+awgHyZQQ62F9mCGxl+iTsE14DJ28MGQ6qrWrnT8Ng0DtHy/e+TCaHw0KBpMfYsx9QBp78g2EUkpDq2C3dk8TJbWQPSIGvrPrqWELbYBRPwCmaTr86H7DX0Sg9WW6N/dUBhM0EXW/MpyxQTNsh1qF/ZOv3QNxi6h/eL/jnx4JegUgbBB3QMHYj9sqfrX1ageFBNlcWw4Y2sD44A0dXw2y+zBTsvhXmZNjQLV6w=" 
  file_glob: true
  file: chromy-$CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^chromy-pax-v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
